version: '3.1'

services:
  starwarsplanets-service:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: mongodb://root:123456@starwarsplanets-mongo:27017/starwars?authSource=admin
      REDIS_PORT: 6379
      REDIS_HOST: starwarsplanets-redis
    depends_on:
      - starwarsplanets-mongo
      - starwarsplanets-redis

  starwarsplanets-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  starwarsplanets-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_SERVER: starwarsplanets-mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

  starwarsplanets-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
