logging:
  level:
    ROOT: INFO
    com.alantech.starwarsplanets: DEBUG

spring:
  application:
    name: "Star Wars Planets - DEV"

  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://root:123456@localhost:27017/starwars?authSource=admin}
      auto-index-creation: true
  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}

application:
  planets-enrichment:
    enabled: false
    cron: "0 0/1 * 1/1 * ?" # every minute
