logging:
  level:
    ROOT: INFO
    com.alantech.starwarsplanets: DEBUG

spring:
  application:
    name: "Star Wars Planets - DEV"
  data:
    mongodb:
      uri: "mongodb://root:123456@localhost:27017/starwars?authSource=admin"
  redis:
    host: "localhost"
    port: 6379

application:
  planets-enrichment:
    enabled: true
    cron: "0 0/1 * 1/1 * ?" # every minute
