spring:
  application:
    name: "Star Wars Planets"
    version: @project.version@
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

server:
  port: 8080

application:
  star-wars-api:
   url: "https://swapi.dev/api/"
   timeout: 3000  # ms
  planets-enrichment:
    enabled: true
    cron: "0 0 0 1/1 * ?" # daily at 00:00
